In [22]:
import numpy as np

In [23]:
a = np.array([
    [0, 1, 0, 0, 1, 0],
    [0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 1],
    [1, 0, 0, 1, 1, 0],
    [1, 0, 0, 1, 1, 0],
    [1, 0, 0, 0, 1, 0]
])
n = a[0].size
b = np.copy(a)

In [24]:
for i in range(1, n):
    for j in range(n):
        if a[i - 1][j] == 1:
            print("Choose Element (", i, ", ", j, ") Of Table")
            if i + 1 < n:
                a[i + 1][j] = 1 if a[i + 1][j] == 0 else 0
            if i - 1 >= 0:
                a[i - 1][j] = 1 if a[i - 1][j] == 0 else 0
            if j + 1 < n: 
                a[i][j + 1] = 1 if a[i][j + 1] == 0 else 0
            if j - 1 >= 0:
                a[i][j - 1] = 1 if a[i][j - 1] == 0 else 0
            a[i][j] = 1 if a[i][j] == 0 else 0
            print(a)
            

Choose Element ( 1 ,  1 ) Of Table
[[0 0 0 0 1 0]
 [1 1 1 1 0 1]
 [1 1 1 0 1 1]
 [1 0 0 1 1 0]
 [1 0 0 1 1 0]
 [1 0 0 0 1 0]]
Choose Element ( 1 ,  4 ) Of Table
[[0 0 0 0 0 0]
 [1 1 1 0 1 0]
 [1 1 1 0 0 1]
 [1 0 0 1 1 0]
 [1 0 0 1 1 0]
 [1 0 0 0 1 0]]
Choose Element ( 2 ,  0 ) Of Table
[[0 0 0 0 0 0]
 [0 1 1 0 1 0]
 [0 0 1 0 0 1]
 [0 0 0 1 1 0]
 [1 0 0 1 1 0]
 [1 0 0 0 1 0]]
Choose Element ( 2 ,  1 ) Of Table
[[0 0 0 0 0 0]
 [0 0 1 0 1 0]
 [1 1 0 0 0 1]
 [0 1 0 1 1 0]
 [1 0 0 1 1 0]
 [1 0 0 0 1 0]]
Choose Element ( 2 ,  2 ) Of Table
[[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [1 0 1 1 0 1]
 [0 1 1 1 1 0]
 [1 0 0 1 1 0]
 [1 0 0 0 1 0]]
Choose Element ( 2 ,  4 ) Of Table
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [1 0 0 1 1 0]
 [1 0 0 0 1 0]]
Choose Element ( 3 ,  0 ) Of Table
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 1 0]
 [1 0 1 1 0 0]
 [0 0 0 1 1 0]
 [1 0 0 0 1 0]]
Choose Element ( 3 ,  2 ) Of Table
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [1 1 0 0 0 0]
 [0 0 1 1 1 0]
 [1 0 0 